### ISSUE TITLE
Is there any reason to create two subnets in the same AZ?

### ISSUE THREAD

**Issue by naxxster** [awslabs/distributed-load-testing-on-aws#43]
When the solution create a VPC and two subnets, the two subnets are located in the same AZ.
I am not sure this is an intended implementation or not.
It would be better to locate in the different AZs, for more reliable test cluster or for more resource capabities.

**Comment by beomseoklee** [comment]
@naxxster Thanks for the feedback. I believe there was no reason to create two subnets in the same AZ, and when I updated the solution, I tried to create in the different AZs, then I realized the updating the solution was not possible somehow (my memory can be wrong). That's why we still have the subnets in the same AZ.

Since we are using Fargate tasks on demand, it would be OK for now I think, but we can revisit this configuration again.
